server:
  port: 9006
spring:
  redis:
    host: 10.0.0.203
    password: Hayll
    port: 6794
    database: 7
  application:
    name: consumer-ticker
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.204:8840
#服务监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
