server:
  port: 9003
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
          - id: abc
            uri: lb://mall-admin-service
            predicates:
             - Path= /admin/**
            filters:
                - RewritePath=/admin(?<segment>/?.*), $\{segment}
management:
  endpoints:
    web:
      exposure:
        include: '*'
