version: '3'
services:
    mysql_db:
        image: mysql:8.0.15
        container_name: mall_db
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: 'root'
            MYSQL_PASS: 'root'
        volumes:
            - "/Users/wangjian/mall_volumns/mall_db:/var/lib/mysql"
    nacos_server:
        image: nacos/nacos-server:latest
        container_name: nacos-standalone
        environment:
            - PREFER_HOST_MODE=hostname
            - MODE=standalone
        volumes:
            - /Users/wangjian/mall_volumns/mall_nacos/logs/:/home/nacos/logs
        ports:
            - "8848:8848"
    elasticsearch:
        image: ws/elasticsearch-with-ik:6.4.3
        container_name: es
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.3
        container_name: kibana
        links:
            - elasticsearch
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: http://0.0.0.0:9200

