server:
    port: 9002
    servlet:
        context-path: /mall_admin
# 服务注册到nacos
spring:
    application:
        name: mall-admin
    cloud:
        nacos:
            discovery:
                server-addr: 10.0.0.204:8840
        sentinel:
            transport:
                port: 8001
                dashboard: 10.0.0.204:8858
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://10.0.0.204:3309/mall?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: root
#服务监控
management:
    endpoints:
        web:
            exposure:
                include: '*'
feign:
    sentinel:
        enabled: true
mybatis-plus:
    global-config:
        db-config:
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
