server:
  port: 9002
# 服务注册到nacos
spring:
  application:
    name: consumer-config
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.204:8840
    sentinel:
      transport:
        port: 8001
        dashboard: 10.0.0.204:8858
#服务监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
debug: true